
 -- ****************************************************************** --
 -- **                  CONCEPTO DE FLASHBACK                       ** --
 -- ****************************************************************** --
 
 -- ** FLASHBACK DROP TABLE
 
 -- Usted puede utilizar Flashback Drop Table, para restaurar una tabla eliminada
 -- por error humano. Para ello hace uso de las funcionalidades de la 
 -- Papelera de Reciclaje.
--- ACTIVE LA PAPELERA DE RECICLAJE
SHOW PARAMETER RECYCLEBIN;

ALTER SESSION SET RECYCLEBIN=ON;

-- CONSULTE LA PAPELERA DE RECICLAJE
SELECT * FROM RECYCLEBIN;


CREATE TABLE NOTAS ( ID INTEGER , N1 INTEGER , N2 INTEGER) ;
INSERT INTO NOTAS VALUES ( 1 , 12 , 15 );
INSERT INTO NOTAS VALUES ( 2 , 18 , 14 );
INSERT INTO NOTAS VALUES ( 3 , 12 , 12 );

COMMIT;

SELECT * FROM NOTAS;

-- ELIMINAR LA TABLA

DROP TABLE NOTAS;

-- CONSULTAR LA PAPELERA DE RECICLAJE

SELECT * FROM RECYCLEBIN;

-- Puede visualizar las tablas dropeadas con nuevo nombre..!!!!

-- CONSULTAR LA TABLA DROPEADA

SELECT * FROM "JASDHUW987JJKHJHK2";

-- RECUPERAR LA TABLA DROPEADA

FLASHBACK TABLE NOTAS TO BEFORE DROP;

SELECT * FROM NOTAS;

-- Tabla recuperada…!!!!! Y papelera de reciclaje vacía.


-- DESDE ACADEMICO, DESACTIVAR LA PAPELERA DE RECICLAJE

ALTER SESSION SET RECYCLEBIN=OFF;

-- CREAR UNA NUEVA TABLA 

CREATE TABLE NOTAS_NEW AS SELECT * FROM NOTAS;

SELECT * FROM NOTAS_NEW;

-- ELIMINAR LA TABLA NOTAS_NEW Y CONSULTE LA PAPELERA DE RECICLAJE

DROP TABLE NOTAS_NEW;

SELECT * FROM RECYCLEBIN;  

-- Debido a que la papelera esta desactivada, no es posible recuperar la tabla.

------------------------------------------------------------------------------
--- MANEJO DE 2 VERSIONES ELIMINADAS DE UNA TABLA
------------------------------------------------------------------------------

-- ACTIVAR LA PAPELERA DE RECICLAJE

ALTER SESSION SET RECYCLEBIN=ON;


-- ELIMINAR LA TABLA “NOTAS”

DROP TABLE NOTAS;

--- CONSULTAR LA PAPELERA DE RECICLAJE

SELECT * FROM RECYCLEBIN;

-- CREAR LA SIGUIENTE TABLA
CREATE TABLE EMPLEADO
(CEDULA NUMBER,
NOMBRE VARCHAR2(30),
EDAD NUMBER);

INSERT INTO EMPLEADO VALUES (100,'PAULA BETANCUR',46);
INSERT INTO EMPLEADO VALUES (200,'LINA MORALES',22);
INSERT INTO EMPLEADO VALUES (300,'MARTIN VELEZ',44);
COMMIT WORK;

--- CREAR UNA NUEVA TABLA “NOTAS”

CREATE TABLE NOTAS AS SELECT * FROM EMPLEADO;

SELECT * FROM NOTAS;

-- ELIMINAR LA TABLA “NOTAS”

DROP TABLE NOTAS;

SELECT * FROM RECYCLEBIN;

-- Se puede apreciar 2 elementos eliminados, consultemos cada versión

--- RECUPERAR LAS TABLAS DROPEADAS

FLASHBACK TABLE "BIN$IQtL04aFVkXgQDabvUJKEw==$0" TO BEFORE DROP
RENAME TO NOTAS01;

FLASHBACK TABLE "BIN$IQJS4aFVkXgQDabvUJKEw==$0" TO BEFORE DROP
RENAME TO NOTAS02;

SELECT * FROM NOTAS01;
SELECT * FROM NOTAS02;




 -- ** FLASHBACK TABLE
 
 -- Usando Flashback Table, se puede recuperar un conjunto de tablas a un punto 
 -- específico en el tiempo sin necesidad de realizar operaciones de 
 -- recuperación de punto en el tiempo tradicionales.
 
 CREATE TABLE ARTICULO  (ID  NUMBER(10) , NOMBRE CHAR(50) );
 
 ALTER TABLE ARTICULO  ENABLE ROW MOVEMENT;
 
 SELECT CURRENT_SCN FROM V$DATABASE; --3695666
 
 INSERT INTO ARTICULO   VALUES (100 , 'QUESOS' );
COMMIT;

SELECT CURRENT_SCN FROM V$DATABASE; --3695697

INSERT INTO ARTICULO   VALUES (200 , 'FIDEOS' );
COMMIT;
SELECT CURRENT_SCN FROM V$DATABASE; --3695827

INSERT INTO ARTICULO   VALUES (300 , 'LICORES' );
COMMIT;
SELECT CURRENT_SCN FROM V$DATABASE; --3695842

SELECT * FROM ARTICULO;

-- RESTAURANDO  

FLASHBACK TABLE ARTICULO   TO SCN 3695842;
SELECT * FROM ARTICULO  ;

 -- ** FLASHBACK VERSION QUERY
 -- Usted puede utilizar Flashback Version Query para recuperar la historia de 
 -- una fila. La característica de Flashback Query versión permite utilizar 
 -- la cláusula VERSIONES para recuperar todas las versiones de las filas que 
 -- hay entre dos puntos en el tiempo o dos SCN.
 
 CREATE TABLE CURSO 
 ( id integer, curso char(50), costo integer, FECHA DATE DEFAULT SYSDATE );

-- CAMBIO 1 
INSERT INTO CURSO VALUES ( 1 , 'ORACLE' , 350, SYSDATE ); 
COMMIT;

SELECT current_scn, TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS') 
FROM v$database; -- 3696227	2023-10-25 19:18:26

-- CAMBIO 2 Y 3
UPDATE CURSO SET CURSO = 'ORACLE 2' WHERE ID = 1 ; -- 3696261	2023-10-25 19:19:32
COMMIT;
UPDATE CURSO SET CURSO = 'ORACLE 3' WHERE ID = 1 ; -- 3696488	2023-10-25 19:21:54
COMMIT;

SELECT current_scn, TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS') 
FROM v$database;

SELECT versions_startscn, versions_starttime, 
       versions_endscn, versions_endtime,
       versions_xid, versions_operation,
       curso  
FROM   curso 
       VERSIONS BETWEEN TIMESTAMP TO_TIMESTAMP('2023-10-25 19:18:26', 'YYYY-MM-DD HH24:MI:SS')
                        AND TO_TIMESTAMP('2023-10-25 19:21:54', 'YYYY-MM-DD HH24:MI:SS')
WHERE  id = 1;

SELECT versions_startscn, versions_starttime, 
       versions_endscn, versions_endtime,
       versions_xid, versions_operation,
       curso 
FROM   curso
       VERSIONS BETWEEN SCN 7802474 AND 7802475
WHERE  id = 1;


-- CONFIGURANDO MODO FLASHBACK

STARTUP MOUNT;
Alter database archivelog;
ALTER SYSTEM SET DB_RECOVERY_FILE_DEST_SIZE = 1G;
ALTER SYSTEM SET DB_RECOVERY_FILE_DEST = '/u02/oracle/fra';
ALTER DATABASE FLASHBACK ON;
ALTER DATABASE OPEN;
-- CONSULTANDO MODO FLASHBACK
SELECT FLASHBACK_ON FROM V$DATABASE; -- ( NO/YES )
-- CONFIGURANDO TIEMPO DE RESGUARDO DE DATOS
ALTER SYSTEM SET DB_FLASHBACK_RETENTION_TARGET=2880;
-- TIEMPO DADO EN MINUTOS

-- GENERANDO ESCENARIO
-- CREANDO TABLE A RECUPERAR
CREATE TABLE PRUEBAFLASH AS SELECT * FROM scott.dept;
COMMIT;
SELECT COUNT(*) FROM PRUEBAFLASH:
-- CONSULTANDO EL SCN
SELECT DBMS_FLASHBACK.GET_SYSTEM_CHANGE_NUMBER FROM DUAL;
--  SCN : 9999
-- BORRANDO LOS REGISTROS
DELETE FROM PRUEBAFLASH;
COMMIT;
SELECT DBMS_FLASHBACK.GET_SYSTEM_CHANGE_NUMBER FROM DUAL;
-- SCN : 19999

-- FLASHBACK LA BD ( RESTAURACION EN UN PUNTO EN EL TIEMPO CON REFERENCIA A SCN )
STARTUP MOUNT:
FLASHBACK DATABASE TO SCN 9999;
ALTER DATABASE OPEN RESETLOGS;

-- TAREA: QUE ES RESETLOGS EN ESTA INSTRUCCIÓN?
-- TAREA: Y COMO SE HACE EL FLASHBACK QUERY A UN PUNTO DEL TIEMPO?
-- QUÉ ES EL ROW MOVEMENT?
-- TAREA: Y QUE ES EL FLASHBACK A NIVEL DE BASE DE DATOS CON RESTORE POINT?


 









