--Crear un nuevo Table Space

CREATE TABLESPACE VENTAS
DATAFILE 'C:/TBS/VENTS.DAT' SIZE 10M;

--CREAR 1 TABLE SPACE CON 2 DATAFILE
CREATE TABLESPACE CONTABILIDAD
DATAFILE 'C:/TBS/CONTABILIDAD1.DAT' SIZE 5M,
         'C:/TBS/CONTABILIDAD2.DAT' SIZE 15M;            
         
SELECT * FROM DBA_TABLESPACES;
SELECT FILE#, NAME FROM V$DATAFILE;
SELECT * FROM DBA_DATA_FILES;

--CADA BLOQUE EN ORACLE ES DE 8192 BYTES (8KB)

--CONSULTAR ESPACIO DISPONIBLE EN UN TABLE SPACE
SELECT * FROM DBA_FREE_SPACE;

--CREAR UN TABLA ASOCIADO A UN TBS
CREATE TABLE ARTICULO(
ID INTEGER,
DESCRIPCION VARCHAR(100)
) TABLESPACE VENTAS;

--INSERTAR 10000 REGISTROS
INSERT INTO ARTICULO
SELECT LEVEL, 'ART' || LEVEL 
FROM DUAL
CONNECT BY LEVEL <= 100000;

COMMIT;

--MODIFICAR EL TAMAÑO DE UN DATAFILE
ALTER DATABASE DATAFILE 'C:/TBS/VENTAS.DAT' RESIZE 50MB;

--AGREGAR UN DATAFILE A UN TABLE SPACE
ALTER TABLESPACE VENTAS ADD DATAFILE 'C:/TBS/VENTAS1.DAT' SIZE 20MB;

--ELIMINAR TABLASPACES
DROP TABLESPACE VENTAS; --BORRAR TABLESPACE SIN CONTENIDO
DROP TABLESPACE VENTAS INCLUDING CONTENTS AND DATAFILES; --BORRAR TABLESPACE CON CONTENIDO Y DATAFILES


--DOS TABLESPACE CON TABLAS RELACIONADAS ENTRE SI
CREATE TABLESPACE EJEMPLO1 
DATAFILE 'C:/TBS/EJEMPLO1.DAT' SIZE 10M;

CREATE TABLESPACE EJEMPLO2 
DATAFILE 'C:/TBS/EJEMPLO2.DAT' SIZE 10M;

CREATE TABLE CARGO(
ID NUMBER PRIMARY KEY,
NOMBRE VARCHAR(30)
)TABLESPACE EJEMPLO1;

CREATE TABLE CARGO(
ID NUMBER PRIMARY KEY,
NOMBRE VARCHAR(30),
CODCARGO NUMBER
)TABLESPACE EJEMPLO2;

ALTER TABLE EMPLEADO
ADD FOREIGN KEY(CODCARGO)
REFERENCES CARGO(ID);

INSERT INTO CARGO VALUES (1, 'GERENTE');
INSERT INTO CARGO VALUES (2, 'SUPERVISOR');

INSERT INTO EMPLEADO VALUES (10, 'JUAN PEREZ', 1);
INSERT INTO EMPLEADO VALUES (20, 'ANA LOPEZ', 2);

DROP TABLESPACE EJEMPLO1 INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

SELECT * FROM EMPLEADO;

--COMPACTAR UN TABLESPACE
CREATE TABLESPACE EJEMPLO3
DATAFILE 'C:/TBS/EJEMPLO3.DAT' SIZE 200M;

CREATE TABLE CURSO1(
ID INTEGER, 
NOMBRE VARCHAR(200)
) TABLESPACE EJEMPLO3;


INSERT INTO CURSO1
SELECT LEVEL, 'CURSO' || LEVEL 
FROM DUAL
CONNECT BY LEVEL <= 500000;

COMMIT;

SELECT COUNT(*) FROM CURSO1;

SELECT SEGMENT_NAME, SEGMENT_TYPE, BYTES/1024/1024, BLOCKS
FROM USER_SEGMENTS
WHERE SEGMENT_NAME='CURSO1';


DELETE FROM CURSO1 WHERE ID <= 250000;

EXEC DBMS_STATS.GATHER_TABLE_STATS('SYSTEM','CURSO1');

--HABILITAR DESFRAGMENTADO PARA LA TABLA ESPECIFICA
ALTER TABLE CURSO1 ENABLE ROW MOVEMENT;

--EJECUTAR DESFRACMENTADO
ALTER TABLE CURSO1 SHRINK SPACE;



--ESTADOS DE UN TABLESPACE
ALTER TABLESPACE EJEMPLO3 READ ONLY;--INACTIVAR ESCRITURA

ALTER TABLESPACE EJEMPLO3 READ WRITE;--VOLVER A ACTIVAR ESCRITURA

SELECT * FROM DBA_TABLESPACES;

ALTER TABLESPACE EJEMPLO3 OFFLINE NORMAL;--INACTIVA LECTURA EN EL TABLE SPACE
--OFFLINE NORMAL ESPERA QUE TODOS LOS USUARIOS TERMINEN LAS TRANSACCIONES Y LUEGO CAMBIA EL TABLESPACE
--OFFLINE INMEDIATE NO ESPERA QUE TODOS LOS USUARIOS TERMINEN LAS TRANSACCIONES (ABORTA PROCESOS)
