CREATE TABLESPACE VENTAS
DATAFILE 'C:/tbs/VENTAS.DAT' SIZE 2M;

CREATE TABLE TABLA1(
DATOS VARCHAR(100)
) TABLESPACE VENTAS;

INSERT INTO TABLA1 VALUES ('AAAAAAAAAAAAAA');

INSERT INTO TABLA1 SELECT * FROM TABLA1;

SELECT * FROM TABLA1;

-- CREAR UN TABLESPACE AUTO EXTENSIBLE
CREATE TABLESPACE FACTURACION
DATAFILE 'C:/TBS/FACTURACION.DAT' 
SIZE 2M
AUTOEXTEND ON
NEXT 1M
MAXSIZE 10M;

CREATE TABLE DATOS1(
CAMPO VARCHAR(100)
) TABLESPACE FACTURACION;

INSERT INTO DATOS1 VALUES ('AAAAAAAAAAAAAA');

INSERT INTO DATOS1 SELECT * FROM DATOS1;

COMMIT;

-- AGREGAR AUTO EXTENSIBLE A UN TALESPACE QUE NO LO TENIA HABILITADO
ALTER DATABASE DATAFILE 'C:/TBS/VENTAS.DAT'
AUTOEXTEND ON
NEXT 2M
MAXSIZE 10M;

--COMO MOVER DATAFILES
ALTER DATABASE MOVE DATAFILE
'C:/TBS/VENTAS.DAT' TO 'C:/TBS1/VENTAS.DAT';


--TABLESPACE TEMPORALES
SELECT * FROM DATABASE_PROPERTIES
WHERE PROPERTY_NAME LIKE '%TEMP%';

CREATE TEMPORARY TABLESPACE TEMP1
TEMPFILE 'C:/TBS/TEMP1.DAT'
SIZE 30M;

-- CAMBIAR TABLESPACE TEMPORAL POR DEFECTO A TEMP1
ALTER DATABASE DEFAULT TEMPORARY TABLESPACE TEMP1;