CREATE TABLE PRODUCTOS(
CODIGO NUMBER PRIMARY KEY,
NOMBRE VARCHAR(30),
PRECIO NUMBER
);

INSERT INTO PRODUCTOS VALUES(1, 'JABON',5000);
INSERT INTO PRODUCTOS VALUES(2, 'ESCOBA',6000);
INSERT INTO PRODUCTOS VALUES(3, 'YOGUSRT',4000);
COMMIT;
SELECT * FROM PRODUCTOS;