-- TODOS LOS PARAMETROS DE CONFIGURACION CON LA PALABRA UNDO
SHOW PARAMETER UNDO

SELECT * FROM DBA_TABLESPACES;

SELECT * FROM dba_data_files WHERE TABLESPACE_NAME = 'UNDOTBS2';

CREATE TABLE TRANSACCIONES(
DATOS VARCHAR2(100)
);

SELECT * FROM V$TRANSACTION; -- VER TRANSACCIONES ACTIVAS DEL USUARIO

INSERT INTO TRANSACCIONES VALUES ('TRANSACCION1');

COMMIT;

CREATE UNDO TABLESPACE UNDOTBS2
DATAFILE 'C:/TEMP/UNDOTBS2.DAT' SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE 200M;


--SIEMPRE HAY UN SOLO TABLESPACE ACTIVO
-- PARA ACTIVAR EL RECIEN CREADO TABLESPACE HACEMOS LOS SIGUIENTE:

ALTER SYSTEM SET UNDO_TABLESPACE = UNDOTBS1
SCOPE = BOTH; -- ES PARA QUE TOME EFECTO DE INMEDIATO, LO GRABA EN EL SPFILE Y EN LA INSTANCIA


ALTER SYSTEM SET UNDO_RETENTION = 1800 SCOPE = BOTH;

ALTER TABLESPACE UNDOTBS2 RETENTION GUARANTEE;